services:
  - type: web
    name: noww-club-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run "app.py" --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false 